name: topcorridafx
version: '0.1.1'
summary: Top Chegada
description: |
  Programa feito em Java / JavaFX, voltado para o atletismo.
base: core18
grade: stable
confinement: strict

apps:
  topcorridafx:
    command: desktop-launch java --module-path=$PATH_TO_FX --add-modules=javafx.controls,javafx.fxml,sqlite.jdbc -classpath ".:$SNAP/sqlite-jdbc-3.27.2.1.jar" -cp $SNAP/jar/TopCorridaFX-0.1.0.jar br.com.topcorridafx.MainApp
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-amd64
      PATH: $JAVA_HOME/jre/bin:$PATH
      PATH_TO_FX: $SNAP/javafx-sdk-11.0.2/lib
    plugs:
      - desktop
      - wayland
      - unity7

parts:
  topcorridafx:
    plugin: maven 
    source: .
    maven-options: [compile]
    build-packages: [openjdk-11-jdk]
    stage-packages: 
      - sqlite3
      - libspring-jdbc-java
      - libsqlite3-0
      - libcanberra-gtk-module
      - openjfx
    after: [desktop-gtk3]

  javafx-11:
    plugin: dump 
    source: snap/local
    stage: 
      - javafx-sdk-11.0.2
      - sqlite-jdbc-3.27.2.1.jar
      - topcorridafx.png
 


  desktop-gtk3:
    build-packages:
    - build-essential
    - libgtk-3-dev
    make-parameters:
    - FLAVOR=gtk3
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    stage-packages:
    - libxkbcommon0
    - ttf-ubuntu-font-family
    - dmz-cursor-theme
    - light-themes
    - adwaita-icon-theme
    - gnome-themes-standard
    - shared-mime-info
    - libgtk-3-0
    - libgdk-pixbuf2.0-0
    - libglib2.0-bin
    - libgtk-3-bin

 


     
