name: topcorridafx
version: '0.1.1'
summary: Top Chegada
description: |
  Programa feito em Java / JavaFX, voltado para o atletismo.
base: core18
grade: stable
confinement: strict

apps:
  topcorridafx:
    command: java --module-path=$PATH_TO_FX --add-modules=javafx.controls,javafx.fxml,sqlite.jdbc -classpath ".:$SNAP/sqlite-jdbc-3.21.0.1.jar" -cp $SNAP/jar/TopCorridaFX-0.1.0.jar br.com.topcorridafx.MainApp
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-amd64
      PATH: $JAVA_HOME/jre/bin:$PATH
      PATH_TO_FX: $SNAP/javafx-sdk-11.0.2/lib
    plugs:
      - desktop
      - wayland
      - unity7

parts:
  topcorridafx:
    plugin: maven 
    source: .
    maven-options: [compile]
    stage-packages:
      - openjdk-11-jdk
      - sqlite3
      - libspring-jdbc-java
      - libsqlite3-0
      - libcanberra-gtk-module
      - openjfx


  javafx-11:
    plugin: dump 
    source: snap/local
    stage: 
      - javafx-sdk-11.0.2
      - sqlite-jdbc-3.21.0.1.jar
      - topcorridafx.png
 
